version: '3.8'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - AZURE_ENV_NAME=${AZURE_ENV_NAME}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000"
    environment:
      - AZURE_ENV_NAME=${AZURE_ENV_NAME}