version: '3.8'

metadata:
  app_name: studiologicapptemplate

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379"
    labels:
      - "studiologic.io.min-replicas=1"
      - "studiologic.io.ingress.internal=true"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - AZURE_ENV_NAME=${AZURE_ENV_NAME}
    depends_on:
      - backend
    labels:
      - "studiologic.io.min-replicas=1"

  backend:
    build:
      context: ./backend
    ports:
      - "5000"
    environment:
      - AZURE_ENV_NAME=${AZURE_ENV_NAME}
    labels:
      - "studiologic.io.min-replicas=1"
      - "studiologic.io.ingress.internal=true"
