version: '3.8'

metadata:
  app_name: studiologicapptemplate

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    # Azure Container Apps ARM template configuration
    x-azure-containerapp:
      properties:
        configuration:
          ingress:
            external: false
            transport: tcp
            targetPort: 6379
            allowInsecure: false
        template:
          scale:
            minReplicas: 1
            maxReplicas: 3
          containers:
            - name: redis
              resources:
                cpu: 0.25
                memory: 0.5Gi

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - AZURE_ENV_NAME=${AZURE_ENV_NAME}
    depends_on:
      - backend
    x-azure-containerapp:
      properties:
        configuration:
          ingress:
            external: true
            transport: http
            targetPort: 8080
            allowInsecure: false
        template:
          scale:
            minReplicas: 1
            maxReplicas: 10
          containers:
            - name: frontend
              resources:
                cpu: 0.5
                memory: 1Gi

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - AZURE_ENV_NAME=${AZURE_ENV_NAME}
    depends_on:
      - redis
    x-azure-containerapp:
      properties:
        configuration:
          ingress:
            external: false
            transport: http
            targetPort: 5000
            allowInsecure: false
        template:
          scale:
            minReplicas: 1
            maxReplicas: 5
          containers:
            - name: backend
              resources:
                cpu: 0.5
                memory: 1Gi
