version: '3.8'

metadata:
  app_name: studiologicapptemplate

services:
  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=myapp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      - "studiologic.io.min-replicas=1"
      - "studiologic.io.ingress.type=internal"
      - "studiologic.io.ingress.transport=tcp"
      - "studiologic.io.storage.type=AzureFile"
      - "studiologic.io.storage.mount-path=/var/lib/postgresql/data"
      - "studiologic.io.storage.share-name=postgres-data"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    labels:
      - "studiologic.io.min-replicas=1"
      - "studiologic.io.ingress.type=internal"
      - "studiologic.io.ingress.transport=tcp"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - AZURE_ENV_NAME=${AZURE_ENV_NAME}
    depends_on:
      - backend
    labels:
      - "studiologic.io.min-replicas=1"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - AZURE_ENV_NAME=${AZURE_ENV_NAME}
      - DATABASE_URL=postgresql://dbuser:dbpassword@postgres:5432/myapp
    depends_on:
      - postgres
    labels:
      - "studiologic.io.min-replicas=1"
      - "studiologic.io.ingress.type=internal"

volumes:
  postgres-data:
