version: '3.8'

metadata:
  app_name: studiologicapptemplate

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    x-azure-containerapp:
      properties:
        configuration:
          ingress:
            external: false
            transport: tcp
            targetPort: 6379
        template:
          scale:
            minReplicas: 1
            maxReplicas: 3

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - AZURE_ENV_NAME=${AZURE_ENV_NAME}
    depends_on:
      - backend
    x-azure-containerapp:
      properties:
        configuration:
          ingress:
            external: true
            transport: http
            targetPort: 8080  # Add this line
        template:
          scale:
            minReplicas: 1
            maxReplicas: 10

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - AZURE_ENV_NAME=${AZURE_ENV_NAME}
      - DATABASE_URL=${DATABASE_URL}  # Add this
    depends_on:
      - redis
    x-azure-containerapp:
      properties:
        configuration:
          ingress:
            external: false
            transport: http
            targetPort: 5000
        template:
          scale:
            minReplicas: 1
            maxReplicas: 5
