name: Azure Cleanup

on:
  workflow_dispatch:
    # Restrict to specific branches
    branches:
      - main
      - staging
      - prod

jobs:
  cleanup:
    runs-on: ubuntu-latest
    # Add a safeguard to ensure we're only running on allowed branches
    if: github.ref_name == 'main' || github.ref_name == 'staging' || github.ref_name == 'prod'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Load App Name from docker-compose.yml
        id: load-app-name
        run: |
          APP_NAME=$(yq '.metadata.app_name' docker-compose.yml | tr '[:upper:]' '[:lower:]') # Convert to lowercase
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT

      - name: Validate App Name
        run: |
          APP_NAME="${{ steps.load-app-name.outputs.app_name }}"
          if [[ ! "$APP_NAME" =~ ^[a-z0-9]+$ ]]; then
            echo "Error: APP_NAME '$APP_NAME' must be lowercase and contain only alphanumeric characters."
            exit 1
          fi
          echo "APP_NAME '$APP_NAME' is valid."

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Generate Resource Group Name
        id: generate-resource-group
        run: |
          # Use the current branch name directly instead of a parameter
          BRANCH_NAME="${{ github.ref_name }}"
          RESOURCE_GROUP="${{ steps.load-app-name.outputs.app_name }}-${BRANCH_NAME}-rg"
          echo "resource_group=$RESOURCE_GROUP" >> $GITHUB_OUTPUT
          echo "Identified resource group to delete: $RESOURCE_GROUP (from branch: $BRANCH_NAME)"

      - name: Delete Resource Group
        run: |
          RESOURCE_GROUP="${{ steps.generate-resource-group.outputs.resource_group }}"
          echo "Deleting Resource Group: $RESOURCE_GROUP"
          az group delete --name $RESOURCE_GROUP --yes --no-wait