name: Azure Cleanup

on:
  workflow_dispatch: # Trigger manually

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      LOCATION: westus
      RESOURCE_GROUP: ${{ github.ref_name == 'main' && 'production-resource-group' || github.ref_name == 'staging' && 'staging-resource-group' || 'dev-resource-group' }}
      ACR_NAME: ${{ github.ref_name == 'main' && 'acrstudiologicioprod' || github.ref_name == 'staging' && 'acrstudiologiciostaging' || 'acrstudiologiciodev' }}
      AZURE_ENV_NAME: ${{ github.ref_name == 'main' && 'production-env' || github.ref_name == 'staging' && 'staging-env' || 'dev-env' }}

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete Container Apps Environment
        run: |
          echo "Deleting Container Apps Environment: ${{ env.AZURE_ENV_NAME }}"
          az containerapp env delete --name ${{ env.AZURE_ENV_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --yes

      - name: Delete ACR
        run: |
          echo "Deleting Azure Container Registry: ${{ env.ACR_NAME }}"
          az acr delete --name ${{ env.ACR_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --yes

      - name: Delete Resource Group
        run: |
          echo "Deleting Resource Group: ${{ env.RESOURCE_GROUP }}"
          az group delete --name ${{ env.RESOURCE_GROUP }} --yes --no-wait